# Este archivo le indica a Dokploy (Nixpacks) c칩mo construir tu aplicaci칩n.

[phases.install]
# Anulamos el comando de instalaci칩n predeterminado (npm ci).
# Ahora usar치 'npm install' en su lugar.
cmds = ["npm install"]
